import DirectorCore

/// Reviewed Simplified Chinese purpose copy for the current user-owned Agent
/// inventory. Every row is bound to the current stable ID, name, and source
/// purpose; source changes therefore fall back safely instead of showing stale
/// Chinese copy.
enum CapabilityPurposeAgentCatalog {
    static let entries: [CapabilityPurposeLocalizationEntry] = [
        entry("agent:global:global-agents:fafe06c492e25001", "Brand Designer", #"Own logo and core visual identity work through evidence-backed discovery, proposal approval, controlled vector production, and logo-system QA."#, "负责 Logo 与核心视觉识别系统：通过有证据支持的调研、提案批准、受控矢量制作和 Logo 系统质检完成交付。"),
        entry("agent:global:global-agents:7cba69d1271dd812", "Creative Producer", #"Own creator-content direction, choose the smallest useful specialist route, resolve conflicts, and integrate one publishable package."#, "负责创作者内容方向，选择最小有效的专业制作路径，解决专业分歧，并整合为可发布的完整成果。"),
        entry("agent:global:global-agents:38b337fa16919f2f", "Frontend Developer", #"Implement approved UX and high-fidelity UI contracts as production interface code, verify the real runtime visually and functionally, and return evidence for independent review."#, "将已批准的 UX 与高保真 UI 契约实现为生产级界面代码，在真实运行环境中验证视觉与功能，并提供证据供独立验收。"),
        entry("agent:global:global-agents:5c33474e3591565b", "Icon Designer", #"Own custom icon batches through mandatory Create Image proposals, explicit user approval, style-specific implementation, and actual-size QA."#, "负责定制图标批次：必须经过 Create Image 提案、用户明确批准、匹配风格的实现和实际尺寸质检。"),
        entry("agent:global:global-agents:93170d050e07312f", "Material Judge", #"Independently assess available media and drafts, select honest proof moments, and expose quality, rights, privacy, or missing-evidence risks."#, "独立评估现有媒体与草稿，选择真实可信的证据片段，并指出质量、权属、隐私或证据缺失风险。"),
        entry("agent:global:global-agents:36da62306a140d2d", "Platform Adapter", #"Adapt one approved core story into platform-native publishing packages without changing its claim, evidence, voice, or visual identity."#, "将已批准的核心故事适配为平台原生发布包，不改变其主张、证据、语气或视觉身份。"),
        entry("agent:global:global-agents:a7376591387f46ff", "Product Architect", #"Turn ambiguous software-product goals into decision-complete architecture, interfaces, trade-offs, migration, rollback, and acceptance criteria."#, "将含糊的软件产品目标转化为决策完备的架构、接口、权衡、迁移、回滚与验收标准。"),
        entry("agent:global:global-agents:5cd2335f3fc509c7", "Product Designer", #"Own user-facing functional scope, journeys, information architecture, interaction, state semantics, accessibility behavior, and UX contracts."#, "负责用户侧功能范围、用户旅程、信息架构、交互、状态语义、无障碍行为与 UX 契约。"),
        entry("agent:global:global-agents:b8faa42908c49695", "Quality Engineer", #"Independently verify software changes against approved requirements and risk controls, collect reproducible evidence, and issue a final passed or blocked decision."#, "根据已批准的需求与风险控制独立验证软件变更，收集可复现证据，并给出通过或阻断结论。"),
        entry("agent:global:global-agents:005fe8b42f8d78be", "Reference Finder", #"Find, visually inspect, compare, and curate real design references into distinct direction lanes with direct sources and explicit coverage."#, "寻找、实际检查、比较并整理真实设计参考，形成不同方向路线，保留直接来源与明确的检查范围。"),
        entry("agent:global:global-agents:b415f3307d309089", "Remotion Engineer", #"Implement approved static designs and motion contracts as deterministic Remotion compositions with reproducible preview and render evidence."#, "将已批准的静态设计与动效契约实现为确定性的 Remotion 合成，并提供可复现的预览与渲染证据。"),
        entry("agent:global:global-agents:be990744a95fa19f", "Review Analyst", #"Independently turn published performance and audience feedback into restrained evidence, confidence limits, and one useful next test."#, "独立分析已发布内容表现与受众反馈，提炼克制的证据、置信边界和一个有价值的后续测试。"),
        entry("agent:global:global-agents:6d95b8b9e7fb3749", "Skill Architect", #"Audit, design, consolidate, retire, and validate user-owned Agent and Skill capabilities without duplication, over-scoping, or unapproved installation."#, "审计、设计、整合、退役并验证用户自有的 Agent 与 Skill，避免重复、范围膨胀或未经批准的安装。"),
        entry("agent:global:global-agents:7bc1b0a338b527af", "Software Engineer", #"Implement approved software changes, verify them, and return evidence. Use for bounded production work; escalate materially risky or repeatedly failing work."#, "实现已批准的软件变更，完成验证并提供证据；负责有边界的生产工作，对重大风险或反复失败的问题升级处理。"),
        entry("agent:global:global-agents:34eb03cdfce4f098", "UI Designer", #"Turn approved product behavior into a coherent, accessible, platform-appropriate high-fidelity interface and implementation-ready visual contract."#, "将已批准的产品行为转化为连贯、无障碍且符合平台特性的高保真界面与可直接实施的视觉契约。"),
        entry("agent:global:global-agents:0f56ad5024229d8c", "Video Director", #"Turn approved material and a communication goal into a clear shot progression, proof structure, framing, rhythm, and editor-ready plan."#, "将已批准的素材与传播目标转化为清晰的镜头推进、证据结构、构图、节奏及可供剪辑执行的计划。"),
        entry("agent:global:global-agents:a4809254566eae2b", "Video Editor", #"Execute an approved shot script: create subtitles and edit picture and sound into a verified video. Use for production, not initial story planning or standalone copywriting."#, "执行已批准的镜头脚本：制作字幕，剪辑画面与声音，并交付经过验证的视频；用于制作，不用于初始故事规划或独立文案创作。"),
        entry("agent:global:global-agents:e6ec0d0fd8489086", "Voice Editor", #"Create truthful, specific social copy by surfacing the strongest audience tension, creator stake, verified proof, and account voice."#, "通过提炼最有力的受众张力、创作者立场、已验证证据与账号语气，创作真实、具体的社交内容文案。"),

        entry("agent:project:project-03d84e40d3db5911:970b1f0034637442", "Director Reviewer", #"Independent senior-design reviewer. Use to assess ownership, design judgment, system depth, evidence quality, and interview risk."#, "独立的高级设计评审者，用于评估负责意识、设计判断、系统深度、证据质量与面试风险。"),
        entry("agent:project:project-03d84e40d3db5911:72cb6e1280436775", "Evidence Editor", #"Evidence and public-safety owner. Use for source collection, traceability, material gaps, ownership checks, and release-safety classification."#, "负责证据与公开安全，用于来源收集、可追溯性、素材缺口、权属核查与发布安全分类。"),
        entry("agent:project:project-03d84e40d3db5911:348dcefa2e51fd88", "Figma Editor", #"Approved Figma write execution owner. Apply scoped text, typography, layout and asset changes; preserve editable nodes; verify results without deciding design direction."#, "负责已批准的 Figma 写入执行：应用限定范围内的文字、字体、布局和素材变更，保留可编辑节点，并在不决定设计方向的前提下验证结果。"),
        entry("agent:project:project-03d84e40d3db5911:c6ba3a3145b2e27e", "Illustration Designer", #"Illustration direction and production owner. Use for semantic concepts, style-controlled raster proposals, user approval, vector conversion, and illustration-system delivery."#, "负责插画方向与制作，用于语义概念、风格受控的位图提案、用户批准、矢量转换和插画系统交付。"),
        entry("agent:project:project-03d84e40d3db5911:6996404c504ac5d4", "Implement Analyst", #"Reference-implementation analyst. Use for DOM, CSS, JavaScript, WebGL, media, scroll-route forensics and bounded reference spikes."#, "负责参考实现分析，用于 DOM、CSS、JavaScript、WebGL、媒体、滚动路径取证以及有边界的参考验证。"),
        entry("agent:project:project-03d84e40d3db5911:ac12e189a36dca05", "Model Designer", #"3D and mockup asset owner. Use for model art direction, device shells, material and lighting, render routes, exports, provenance, and implementation handoff."#, "负责 3D 与样机素材，用于模型艺术指导、设备外壳、材质与灯光、渲染路线、导出、来源记录和实现交接。"),
        entry("agent:project:project-03d84e40d3db5911:dfc049444a2f1682", "Motion Designer", #"Motion production owner. Use for reference reconstruction, scroll choreography, ProtoPie interaction, approved After Effects work, vector-motion conversion, and Figma playback delivery."#, "负责动效制作，用于参考重构、滚动编排、ProtoPie 交互、已批准的 After Effects 工作、矢量动效转换和 Figma 播放交付。"),
        entry("agent:project:project-b22d22ea4c868e2f:dfc049444a2f1682", "Motion Designer", #"Motion-system specialist. Use with $design-motion-behavior for loops, timing, posters, playback states, reduced motion, fallbacks, encoding constraints, and performance budgets."#, "动效系统专家，配合 $design-motion-behavior 处理循环、时序、海报帧、播放状态、减弱动效、回退方案、编码约束和性能预算。"),
        entry("agent:project:project-03d84e40d3db5911:48384927b6a7befb", "Portfolio Director", #"Portfolio routing owner. Use to identify the current stage, assign one primary owner, define review gates, and coordinate formal stage decisions."#, "负责作品集流程路由，用于识别当前阶段、指定一名主要负责人、定义评审门槛并协调正式阶段决策。"),
        entry("agent:project:project-03d84e40d3db5911:ddbe28b7c9e1912f", "Recruiter Reviewer", #"Independent recruiter-screen reviewer. Use for a clean first-pass assessment of resume clarity, role fit, keywords, and one-page hiring risk."#, "独立的招聘筛选评审者，用于首次评估简历清晰度、岗位匹配、关键词与单页招聘风险。"),
        entry("agent:project:project-03d84e40d3db5911:a0e1c4c44cbd2b2e", "Reference Finder", #"Design reference discovery owner. Use to find, visually inspect, compare, and curate real design work across UI, brand, web, editorial, motion, illustration, 3D, data visualization, print, packaging, and related fields."#, "负责设计参考发现，用于在 UI、品牌、网页、编辑设计、动效、插画、3D、数据可视化、印刷、包装等领域寻找、实际检查、比较并整理真实设计作品。"),
        entry("agent:project:project-03d84e40d3db5911:2000cead2e389e03", "Resume Editor", #"Resume production owner. Use to rewrite, compress, tailor, and version application-ready resume content from confirmed facts and reviewer feedback."#, "负责简历制作，根据已确认事实和评审反馈，重写、压缩、定制并版本化可直接投递的简历内容。"),
        entry("agent:project:project-b22d22ea4c868e2f:9c69a7146f37dc11", "Software Engineer", #"Production implementation specialist. Use with $implement-skin-runtime to turn an approved handoff into tested renderer, CDP, macOS, Windows, recovery, and build changes."#, "生产实现专家，配合 $implement-skin-runtime 将已批准的交接转化为经过测试的渲染器、CDP、macOS、Windows、恢复和构建变更。"),
        entry("agent:project:project-03d84e40d3db5911:63371b41e762c03d", "Story Designer", #"Portfolio narrative owner. Use for research synthesis, problem framing, case-study narrative, interview storyline, deck structure, and evidence-gap analysis."#, "负责作品集叙事，用于研究综合、问题框定、案例叙事、面试故事线、演示文稿结构和证据缺口分析。"),
        entry("agent:project:project-b22d22ea4c868e2f:f56b1820f3ec6e83", "System Architect", #"Central architecture and delivery coordinator. Use with $govern-project-architecture to scope work, assign non-overlapping ownership, freeze design contracts, integrate evidence, and keep durable project state."#, "总体架构与交付协调者，配合 $govern-project-architecture 界定工作范围、分配不重叠的职责、冻结设计契约、整合证据并维护持久项目状态。"),
        entry("agent:project:project-03d84e40d3db5911:5c882ed92ad8dda1", "System Designer", #"Design-system governance owner. Use for token architecture, Figma Variables and Modes, component rules, guidelines, migration maps, and deprecation plans."#, "负责设计系统治理，用于令牌架构、Figma Variables 与 Modes、组件规则、指南、迁移图和弃用计划。"),
        entry("agent:project:project-03d84e40d3db5911:08bbf322fa31a17a", "Tooling Engineer", #"Figma plugin implementation owner. Use for project-local plugin code, bridge and schema work, build/test infrastructure, and deterministic HTML-to-Figma conversion maintenance."#, "负责 Figma 插件实现，用于项目内插件代码、桥接与模式、构建测试基础设施，以及确定性的 HTML 到 Figma 转换维护。"),
        entry("agent:project:project-03d84e40d3db5911:f03d50aea19fb5b2", "UI Designer", #"Product UI design owner. Use for approved high-fidelity screen hierarchy, layout, typography, color, components, visual states, responsive presentation, and UI contracts."#, "负责产品 UI 设计，用于已批准的高保真界面层级、布局、字体、色彩、组件、视觉状态、响应式呈现和 UI 契约。"),
        entry("agent:project:project-b22d22ea4c868e2f:f03d50aea19fb5b2", "UI Designer", #"Codex skin interface specialist. Use with $design-skin-interface for route matrices, semantic tokens, scrims, readability, accessibility, and native interaction states."#, "Codex 皮肤界面专家，配合 $design-skin-interface 处理路由矩阵、语义令牌、遮罩、可读性、无障碍和原生交互状态。"),
        entry("agent:project:project-03d84e40d3db5911:2eeccea066c83f2d", "UX Designer", #"Portfolio UX owner. Use for user journeys, information architecture, task flows, interaction rationale, states, friction, and before-and-after experience analysis."#, "负责作品集 UX，用于用户旅程、信息架构、任务流程、交互依据、状态、摩擦点和改版前后体验分析。"),
        entry("agent:project:project-03d84e40d3db5911:1e057b0a2f30fe4b", "Visual Analyst", #"Read-only visual-direction analyst. Use after a reference lane is selected to translate content, existing UI, and inspected references into project-specific direction theses."#, "只读的视觉方向分析者，在参考路线选定后，将内容、现有 UI 与已检查参考转化为项目专属的方向主张。"),
        entry("agent:project:project-03d84e40d3db5911:37134f5f15b1b9d4", "Visual Designer", #"Portfolio visual-production owner. Use for visual language, key visuals, covers, deck composition, screenshot packaging, typography, and presentation-ready static assets."#, "负责作品集视觉制作，用于视觉语言、主视觉、封面、演示文稿构图、截图包装、字体和可直接展示的静态素材。"),
        entry("agent:project:project-b22d22ea4c868e2f:37134f5f15b1b9d4", "Visual Designer", #"Visual-language specialist. Use with $define-visual-language for art direction, composition, palette, material, lighting, posters, and licensed asset specifications."#, "视觉语言专家，配合 $define-visual-language 处理艺术指导、构图、色板、材质、光照、海报和授权素材规范。"),
        entry("agent:project:project-03d84e40d3db5911:cb841022077753ee", "Visual Reviewer", #"Independent visual-fidelity reviewer. Use to compare approved targets with Figma, HTML, rendered, motion, or converted outputs."#, "独立的视觉保真度评审者，用于将已批准目标与 Figma、HTML、渲染、动效或转换后的输出进行比较。"),
        entry("agent:project:project-03d84e40d3db5911:89edc5fec6e12166", "Web Architect", #"Independent web-route reviewer. Use after repeated fidelity failures to decide continue, partial rebuild, full rebuild, or isolated spike."#, "独立的网页技术路线评审者，在多次保真度失败后，用于决定继续、部分重建、完整重建或开展隔离验证。"),
        entry("agent:project:project-03d84e40d3db5911:a19146745655712d", "Website Designer", #"Portfolio web-experience design owner. Use for homepage and case-study IA, scrolling narrative, modules, responsive experience, effects purpose, and developer-ready design briefs."#, "负责作品集网站体验设计，用于首页与案例信息架构、滚动叙事、模块、响应式体验、效果目的和可供开发执行的设计简报。"),
        entry("agent:project:project-03d84e40d3db5911:18c652ae3cc8e2a4", "Website Developer", #"Portfolio frontend implementation owner. Use after design approval for site code, responsive behavior, interaction and effects implementation, local verification, and implementation fixes from visual QA."#, "负责作品集前端实现，在设计批准后处理网站代码、响应式行为、交互与效果实现、本地验证，以及依据视觉 QA 修复实现问题。"),
        entry("agent:global:global-agents:2ef039a98ebf83f8", "Figma Editor", #"Approved Figma write execution owner. Apply scoped text, typography, layout, component, and asset changes while preserving editable structure and verifying the result."#, "负责已批准的 Figma 写入执行：在限定范围内调整文字、字体、布局、组件与素材，同时保留可编辑结构并验证结果。"),
        entry("agent:project:project-381f0830eb8e7e1c:1aacbc47b7a1f0ba", "Soul Companion", #"Handle Soul conversations, candidate discovery, and person-specific context within the project's permission and privacy boundaries."#, "在项目的授权与隐私边界内处理 Soul 对话、候选发现和针对具体对象的上下文。"),
    ]

    private static func entry(
        _ resourceID: String,
        _ sourceName: String,
        _ sourcePurpose: String,
        _ chinesePurpose: String
    ) -> CapabilityPurposeLocalizationEntry {
        CapabilityPurposeLocalizationEntry(
            resourceID: resourceID,
            kind: .agent,
            sourceName: sourceName,
            sourcePurpose: sourcePurpose,
            chinesePurpose: chinesePurpose
        )
    }
}
