import DirectorCore

/// Reviewed Simplified Chinese purpose copy for the current user-owned Agent
/// inventory. Every row is bound to the current stable ID, name, and source
/// purpose; source changes therefore fall back safely instead of showing stale
/// Chinese copy.
enum CapabilityPurposeAgentCatalog {
    static let entries: [CapabilityPurposeLocalizationEntry] = [
        entry("agent:global:global-agents:fafe06c492e25001", "Brand Designer", #"Own visual brand identity work centered on logos and core marks. Translate an approved brand or product strategy into original concept territories, maintain an inspected and explicitly approved reference direction plus an exact proposal approval record, direct controlled vector production, and return a usable logo syst"#, "负责以 Logo 和核心标志为中心的视觉品牌识别工作：把已批准的品牌或产品策略转化为原创概念方向，保留经检查并明确批准的参考方向与提案记录，指导受控的矢量制作，并交付可用的 Logo 系统。"),
        entry("agent:global:global-agents:7cba69d1271dd812", "Creative Producer", #"Own the editorial decision for a creator account: define the audience promise, choose the smallest useful production route, resolve specialist conflicts, and accept the final publishable package."#, "负责创作者账号的编辑决策：定义受众承诺，选择最小有效制作路径，解决专业分歧并验收最终可发布成果。"),
        entry("agent:global:global-agents:38b337fa16919f2f", "Frontend Developer", #"Implement approved product and visual contracts as production interface code with high visual fidelity, native platform behavior, accessibility, performance, and evidence-backed runtime verification. Own the presentation-layer implementation without redesigning what the product does or self-approving the result."#, "将已批准的产品与视觉契约实现为生产级界面代码，保证视觉保真度、平台原生行为、无障碍和性能，并提供基于证据的运行验证；负责表现层实现，不重新定义产品功能，也不自行批准结果。"),
        entry("agent:global:global-agents:5c33474e3591565b", "Icon Designer", #"Own custom icon design as a specialist production task. Translate an approved product or visual need into a coherent icon family, select one matching icon style Skill, enforce a mandatory Create Image proposal and user-approval gate for every batch, and then return editable assets with actual-size QA to the parent UI, "#, "负责专业的自定义图标设计：把已批准的产品或视觉需求转化为统一的图标家族，为每批图标选择一种匹配的样式 Skill，并强制经过 Create Image 提案与用户批准，再将带实际尺寸质检的可编辑素材交回上游界面负责人。"),
        entry("agent:global:global-agents:93170d050e07312f", "Material Judge", #"Determine what the available material can genuinely support, find the strongest publishable moments, and expose missing evidence before scripting begins."#, "判断现有素材能够真实支撑什么，在开始脚本前找出最有力的可发布片段并暴露证据缺口。"),
        entry("agent:global:global-agents:36da62306a140d2d", "Platform Adapter", #"Turn an approved core story into platform-native publishing packages while preserving its claim, evidence, account voice, and visual identity."#, "将已批准的核心故事转化为适配各平台的发布包，同时保留其主张、证据、账号语气与视觉身份。"),
        entry("agent:global:global-agents:a7376591387f46ff", "Product Architect", #"Turn ambiguous software-product requests into decision-complete architecture that is proportionate to the real problem, explicit about trade-offs, and ready for design and implementation."#, "将含糊的软件产品需求转化为决策完备的架构，使其匹配真实问题、明确权衡，并可直接进入设计与实现。"),
        entry("agent:global:global-agents:5cd2335f3fc509c7", "Product Designer", #"Turn product goals and system capabilities into clear, coherent, accessible functional experiences and testable prototypes. Own what the interface must enable and how it behaves; hand approved behavior to `UI Designer` for final visual expression when material visual decisions remain."#, "将产品目标与系统能力转化为清晰、连贯、无障碍的功能体验和可测试原型；负责界面必须支持什么以及如何运作，若仍有重要视觉决策，则把已批准的行为交给 `UI Designer` 完成最终视觉表达。"),
        entry("agent:global:global-agents:b8faa42908c49695", "Quality Engineer", #"Independently determine whether a software change satisfies its stated requirements and risk controls, using reproducible evidence and a final result of `passed` or `blocked`."#, "使用可复现证据独立判断软件变更是否满足既定需求与风险控制，并给出 `passed` 或 `blocked` 的最终结论。"),
        entry("agent:global:global-agents:005fe8b42f8d78be", "Reference Finder", #"Find, visually inspect, compare, and curate real design references that help a user choose a visual direction faster. Work across product UI, websites, brand identity, portfolio and case-study presentation, editorial, typography, print, packaging, motion, illustration, icons, data visualization, 3D, spatial design, and"#, "寻找、实际检查、比较并整理真实设计参考，帮助用户更快选择视觉方向；覆盖产品 UI、网站、品牌识别、作品集与案例呈现、编辑设计、字体、印刷、包装、动效、插画、图标、数据可视化、3D 与空间设计等领域。"),
        entry("agent:global:global-agents:b415f3307d309089", "Remotion Engineer", #"Turn approved static designs, motion contracts, and shot requirements into maintainable, deterministic Remotion compositions with reproducible preview and render evidence. Own the technical motion implementation without taking over content strategy, art direction, or independent quality approval."#, "将已批准的静态设计、动效契约与镜头要求转化为可维护、确定性的 Remotion 合成，并提供可复现的预览与渲染证据；负责技术动效实现，不接管内容策略、艺术指导或独立质量验收。"),
        entry("agent:global:global-agents:be990744a95fa19f", "Review Analyst", #"Turn published performance and audience feedback into restrained, reusable evidence for the next content decision."#, "将已发布内容的表现与受众反馈转化为克制、可复用的证据，服务下一次内容决策。"),
        entry("agent:global:global-agents:6d95b8b9e7fb3749", "Skill Architect", #"Design and maintain user-owned Agent and Skill capabilities without creating duplicate, over-scoped, or untested assets. Turn a capability request into an evidence-backed decision, obtain approval, and then coordinate implementation and validation."#, "设计并维护用户自有的 Agent 与 Skill，避免创建重复、范围过大或未经测试的能力；将能力请求转化为有证据支持的决策，获得批准后协调实现与验证。"),
        entry("agent:global:global-agents:7bc1b0a338b527af", "Software Engineer", #"Implement approved software changes with minimal, correct, maintainable diffs and provide concrete verification evidence without expanding scope or self-approving the result."#, "以最小、正确且可维护的差异实施已批准的软件变更，并提供具体的验证证据，不扩大范围，也不自行批准结果。"),
        entry("agent:global:global-agents:34eb03cdfce4f098", "UI Designer", #"Turn an approved functional experience into a coherent, accessible, platform-appropriate high-fidelity interface. Own how approved priorities and behaviors are expressed visually without changing what the product does."#, "将已批准的功能体验转化为连贯、无障碍且符合平台特性的高保真界面；负责以视觉方式表达既定优先级和行为，不改变产品功能。"),
        entry("agent:global:global-agents:0f56ad5024229d8c", "Video Director", #"Turn available material and a communication goal into a clear visual progression. Make the result understandable through images before relying on narration."#, "将现有素材与传播目标转化为清晰的视觉推进，在依赖旁白之前先让画面本身完成表达。"),
        entry("agent:global:global-agents:a4809254566eae2b", "Video Editor", #"Turn an approved shot script and actual source media into a finished, editable video. Create the subtitles from the shot script as part of production, implement the picture and sound edit, and return verifiable deliverables. Own execution decisions within the approved story and style."#, "将已批准的镜头脚本与真实源素材制作成完成且可编辑的视频；制作脚本字幕，完成画面与声音剪辑，并交付可验证成果。在已批准的故事与风格内负责执行决策。"),
        entry("agent:global:global-agents:e6ec0d0fd8489086", "Voice Editor", #"Turn the truth of the available material into copy that earns the viewer's next second. Find the most specific, consequential, or relatable angle in the material; give titles, on-screen text, spoken lines, and captions distinct jobs; and create semantic progression without inventing a story or leaving the current accou"#, "将素材中的真实内容转化为能赢得观众下一秒注意的文案；找到最具体、重要或有共鸣的角度，让标题、画面文字、口播与字幕各司其职，在不编造故事或偏离当前账号语气的前提下形成语义推进。"),

        entry("agent:project:project-03d84e40d3db5911:970b1f0034637442", "Director Reviewer", #"Independent senior-design reviewer. Use to assess ownership, design judgment, system depth, evidence quality, and interview risk."#, "独立的高级设计评审者，用于评估负责意识、设计判断、系统深度、证据质量与面试风险。"),
        entry("agent:project:project-03d84e40d3db5911:72cb6e1280436775", "Evidence Editor", #"Evidence and public-safety owner. Use for source collection, traceability, material gaps, ownership checks, and release-safety classification."#, "负责证据与公开安全，用于来源收集、可追溯性、素材缺口、权属核查与发布安全分类。"),
        entry("agent:project:project-03d84e40d3db5911:348dcefa2e51fd88", "Figma Editor", #"Approved Figma write execution owner. Apply scoped text, typography, layout and asset changes; preserve editable nodes; verify results without deciding design direction."#, "负责已批准的 Figma 写入执行：应用限定范围内的文字、字体、布局和素材变更，保留可编辑节点，并在不决定设计方向的前提下验证结果。"),
        entry("agent:project:project-03d84e40d3db5911:c6ba3a3145b2e27e", "Illustration Designer", #"Illustration direction and production owner. Use for semantic concepts, style-controlled raster proposals, user approval, vector conversion, and illustration-system delivery."#, "负责插画方向与制作，用于语义概念、风格受控的位图提案、用户批准、矢量转换和插画系统交付。"),
        entry("agent:project:project-03d84e40d3db5911:6996404c504ac5d4", "Implement Analyst", #"Reference-implementation analyst. Use for DOM, CSS, JavaScript, WebGL, media, scroll-route forensics and bounded reference spikes."#, "负责参考实现分析，用于 DOM、CSS、JavaScript、WebGL、媒体、滚动路径取证以及有边界的参考验证。"),
        entry("agent:project:project-03d84e40d3db5911:ac12e189a36dca05", "Model Designer", #"3D and mockup asset owner. Use for model art direction, device shells, material and lighting, render routes, exports, provenance, and implementation handoff."#, "负责 3D 与样机素材，用于模型艺术指导、设备外壳、材质与灯光、渲染路线、导出、来源记录和实现交接。"),
        entry("agent:project:project-03d84e40d3db5911:dfc049444a2f1682", "Motion Designer", #"Motion production owner. Use for reference reconstruction, scroll choreography, ProtoPie interaction, approved After Effects work, vector-motion conversion, and Figma playback delivery."#, "负责动效制作，用于参考重构、滚动编排、ProtoPie 交互、已批准的 After Effects 工作、矢量动效转换和 Figma 播放交付。"),
        entry("agent:project:project-b22d22ea4c868e2f:dfc049444a2f1682", "Motion Designer", #"Motion-system specialist. Use with $design-motion-behavior for loops, timing, posters, playback states, reduced motion, fallbacks, encoding constraints, and performance budgets."#, "动效系统专家，配合 $design-motion-behavior 处理循环、时序、海报帧、播放状态、减弱动效、回退方案、编码约束和性能预算。"),
        entry("agent:project:project-03d84e40d3db5911:48384927b6a7befb", "Portfolio Director", #"Portfolio routing owner. Use to identify the current stage, assign one primary owner, define review gates, and coordinate formal stage decisions."#, "负责作品集流程路由，用于识别当前阶段、指定一名主要负责人、定义评审门槛并协调正式阶段决策。"),
        entry("agent:project:project-03d84e40d3db5911:ddbe28b7c9e1912f", "Recruiter Reviewer", #"Independent recruiter-screen reviewer. Use for a clean first-pass assessment of resume clarity, role fit, keywords, and one-page hiring risk."#, "独立的招聘筛选评审者，用于首次评估简历清晰度、岗位匹配、关键词与单页招聘风险。"),
        entry("agent:project:project-03d84e40d3db5911:a0e1c4c44cbd2b2e", "Reference Finder", #"Design reference discovery owner. Use to find, visually inspect, compare, and curate real design work across UI, brand, web, editorial, motion, illustration, 3D, data visualization, print, packaging, and related fields."#, "负责设计参考发现，用于在 UI、品牌、网页、编辑设计、动效、插画、3D、数据可视化、印刷、包装等领域寻找、实际检查、比较并整理真实设计作品。"),
        entry("agent:project:project-03d84e40d3db5911:2000cead2e389e03", "Resume Editor", #"Resume production owner. Use to rewrite, compress, tailor, and version application-ready resume content from confirmed facts and reviewer feedback."#, "负责简历制作，根据已确认事实和评审反馈，重写、压缩、定制并版本化可直接投递的简历内容。"),
        entry("agent:project:project-b22d22ea4c868e2f:9c69a7146f37dc11", "Software Engineer", #"Production implementation specialist. Use with $implement-skin-runtime to turn an approved handoff into tested renderer, CDP, macOS, Windows, recovery, and build changes."#, "生产实现专家，配合 $implement-skin-runtime 将已批准的交接转化为经过测试的渲染器、CDP、macOS、Windows、恢复和构建变更。"),
        entry("agent:project:project-03d84e40d3db5911:63371b41e762c03d", "Story Designer", #"Portfolio narrative owner. Use for research synthesis, problem framing, case-study narrative, interview storyline, deck structure, and evidence-gap analysis."#, "负责作品集叙事，用于研究综合、问题框定、案例叙事、面试故事线、演示文稿结构和证据缺口分析。"),
        entry("agent:project:project-b22d22ea4c868e2f:f56b1820f3ec6e83", "System Architect", #"Central architecture and delivery coordinator. Use with $govern-project-architecture to scope work, assign non-overlapping ownership, freeze design contracts, integrate evidence, and keep durable project state."#, "总体架构与交付协调者，配合 $govern-project-architecture 界定工作范围、分配不重叠的职责、冻结设计契约、整合证据并维护持久项目状态。"),
        entry("agent:project:project-03d84e40d3db5911:5c882ed92ad8dda1", "System Designer", #"Design-system governance owner. Use for token architecture, Figma Variables and Modes, component rules, guidelines, migration maps, and deprecation plans."#, "负责设计系统治理，用于令牌架构、Figma Variables 与 Modes、组件规则、指南、迁移图和弃用计划。"),
        entry("agent:project:project-03d84e40d3db5911:08bbf322fa31a17a", "Tooling Engineer", #"Figma plugin implementation owner. Use for project-local plugin code, bridge and schema work, build/test infrastructure, and deterministic HTML-to-Figma conversion maintenance."#, "负责 Figma 插件实现，用于项目内插件代码、桥接与模式、构建测试基础设施，以及确定性的 HTML 到 Figma 转换维护。"),
        entry("agent:project:project-03d84e40d3db5911:f03d50aea19fb5b2", "UI Designer", #"Product UI design owner. Use for approved high-fidelity screen hierarchy, layout, typography, color, components, visual states, responsive presentation, and UI contracts."#, "负责产品 UI 设计，用于已批准的高保真界面层级、布局、字体、色彩、组件、视觉状态、响应式呈现和 UI 契约。"),
        entry("agent:project:project-b22d22ea4c868e2f:f03d50aea19fb5b2", "UI Designer", #"Codex skin interface specialist. Use with $design-skin-interface for route matrices, semantic tokens, scrims, readability, accessibility, and native interaction states."#, "Codex 皮肤界面专家，配合 $design-skin-interface 处理路由矩阵、语义令牌、遮罩、可读性、无障碍和原生交互状态。"),
        entry("agent:project:project-03d84e40d3db5911:2eeccea066c83f2d", "UX Designer", #"Portfolio UX owner. Use for user journeys, information architecture, task flows, interaction rationale, states, friction, and before-and-after experience analysis."#, "负责作品集 UX，用于用户旅程、信息架构、任务流程、交互依据、状态、摩擦点和改版前后体验分析。"),
        entry("agent:project:project-03d84e40d3db5911:1e057b0a2f30fe4b", "Visual Analyst", #"Read-only visual-direction analyst. Use after a reference lane is selected to translate content, existing UI, and inspected references into project-specific direction theses."#, "只读的视觉方向分析者，在参考路线选定后，将内容、现有 UI 与已检查参考转化为项目专属的方向主张。"),
        entry("agent:project:project-03d84e40d3db5911:37134f5f15b1b9d4", "Visual Designer", #"Portfolio visual-production owner. Use for visual language, key visuals, covers, deck composition, screenshot packaging, typography, and presentation-ready static assets."#, "负责作品集视觉制作，用于视觉语言、主视觉、封面、演示文稿构图、截图包装、字体和可直接展示的静态素材。"),
        entry("agent:project:project-b22d22ea4c868e2f:37134f5f15b1b9d4", "Visual Designer", #"Visual-language specialist. Use with $define-visual-language for art direction, composition, palette, material, lighting, posters, and licensed asset specifications."#, "视觉语言专家，配合 $define-visual-language 处理艺术指导、构图、色板、材质、光照、海报和授权素材规范。"),
        entry("agent:project:project-03d84e40d3db5911:cb841022077753ee", "Visual Reviewer", #"Independent visual-fidelity reviewer. Use to compare approved targets with Figma, HTML, rendered, motion, or converted outputs."#, "独立的视觉保真度评审者，用于将已批准目标与 Figma、HTML、渲染、动效或转换后的输出进行比较。"),
        entry("agent:project:project-03d84e40d3db5911:89edc5fec6e12166", "Web Architect", #"Independent web-route reviewer. Use after repeated fidelity failures to decide continue, partial rebuild, full rebuild, or isolated spike."#, "独立的网页技术路线评审者，在多次保真度失败后，用于决定继续、部分重建、完整重建或开展隔离验证。"),
        entry("agent:project:project-03d84e40d3db5911:a19146745655712d", "Website Designer", #"Portfolio web-experience design owner. Use for homepage and case-study IA, scrolling narrative, modules, responsive experience, effects purpose, and developer-ready design briefs."#, "负责作品集网站体验设计，用于首页与案例信息架构、滚动叙事、模块、响应式体验、效果目的和可供开发执行的设计简报。"),
        entry("agent:project:project-03d84e40d3db5911:18c652ae3cc8e2a4", "Website Developer", #"Portfolio frontend implementation owner. Use after design approval for site code, responsive behavior, interaction and effects implementation, local verification, and implementation fixes from visual QA."#, "负责作品集前端实现，在设计批准后处理网站代码、响应式行为、交互与效果实现、本地验证，以及依据视觉 QA 修复实现问题。"),
    ]

    private static func entry(
        _ resourceID: String,
        _ sourceName: String,
        _ sourcePurpose: String,
        _ chinesePurpose: String
    ) -> CapabilityPurposeLocalizationEntry {
        CapabilityPurposeLocalizationEntry(
            resourceID: resourceID,
            kind: .agent,
            sourceName: sourceName,
            sourcePurpose: sourcePurpose,
            chinesePurpose: chinesePurpose
        )
    }
}
